api:
  version: 1.0.0

server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ip:port/wpdiy?useSSL=false
    username: username
    password: password
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: wang.sj.wpdiy.entity